import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#18301d",
        "primary-container": "#2e4632",
        "primary-fixed": "#cdeace",
        "primary-fixed-dim": "#b2ceb3",
        "on-primary": "#ffffff",
        "on-primary-container": "#98b39a",
        "on-primary-fixed": "#08200f",
        secondary: "#54606a",
        "secondary-container": "#d7e4f0",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5a6670",
        tertiary: "#39270f",
        "tertiary-container": "#513d23",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c5a887",
        surface: "#fbf9f4",
        "surface-dim": "#dbdad5",
        "surface-bright": "#fbf9f4",
        "surface-variant": "#e4e2dd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container": "#f0eee9",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#434842",
        background: "#fbf9f4",
        "on-background": "#1b1c19",
        outline: "#737971",
        "outline-variant": "#c3c8c0",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f1ec",
        "inverse-primary": "#b2ceb3",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        serif: ["Noto Serif", "Georgia", "serif"],
        sans: ["Manrope", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
